"""v0.9.6 add ON DELETE CASCADE to user-owned FKs

Revision ID: b8d6f3e92c14
Revises: a7c5e2f81d20
Create Date: 2026-05-16 19:30:00.000000

Background: until v0.9.6, no foreign key declared an ON DELETE action,
so Postgres / MySQL defaulted to NO ACTION (RESTRICT). The practical
effect: deleting a User raised IntegrityError because every child row
blocked it. Account deactivation (`is_active=False`) was the only
safe path.

This migration adds ON DELETE CASCADE to every user-owned FK across
all 12 child tables. After this, deleting a User row deletes their
transactions, plans, budgets, tags, debts, payments, notifications,
trips, investments, savings goals, AI recommendations, and
preferences atomically.

GDPR-relevant: this is the schema underpinning of an eventual
"delete my account" endpoint. The endpoint itself isn't added in
this migration — flipping `is_active=False` is still the recommended
soft-delete path — but the schema is now ready.

Compatibility:
- PostgreSQL: native ALTER CONSTRAINT replacement via batch.
- MySQL/MariaDB: same DDL, FK name auto-generated by InnoDB.
- SQLite: requires CREATE-rename-COPY-DROP dance via batch_alter_table.

FK name discovery: we use SQLAlchemy's Inspector to look up the real
constraint name at migration time rather than guessing. Earlier
versions of this migration tried 3 name patterns inside a try/except,
which on Postgres can poison the surrounding transaction when one of
the guesses fails — the next op in the same batch then fails too.
Inspector-based lookup avoids that whole class of bug.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


revision: str = "b8d6f3e92c14"
down_revision: Union[str, Sequence[str], None] = "a7c5e2f81d20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (table, column, target_table) for every user-owned FK in the schema.
_USER_FK_TABLES: list[tuple[str, str, str]] = [
    ("transactions", "user_id", "users"),
    ("plans", "user_id", "users"),
    ("budgets", "user_id", "users"),
    ("payments", "user_id", "users"),
    ("notifications", "user_id", "users"),
    ("trips", "user_id", "users"),
    ("investments", "user_id", "users"),
    ("user_preferences", "user_id", "users"),
    ("savings_goals", "user_id", "users"),
    ("debts", "user_id", "users"),
    ("ai_recommendations", "user_id", "users"),
    ("tags", "user_id", "users"),
]

# Canonical name we give the new FK on every dialect. Lets downgrade
# find it again without inspector calls.
def _new_fk_name(table: str, column: str) -> str:
    return f"{table}_{column}_fkey"


def _existing_fk_name(table: str, column: str) -> str | None:
    """Look up the real constraint name for ``(table, column) →
    users.id`` via the live introspector. Returns None if no FK matches,
    which on a populated DB means the schema is unexpected — we'd rather
    fail loudly than silently create a duplicate."""
    bind = op.get_bind()
    insp = inspect(bind)
    for fk in insp.get_foreign_keys(table):
        if fk.get("referred_table") == "users" and column in (fk.get("constrained_columns") or []):
            return fk.get("name")
    return None


def upgrade() -> None:
    for table, column, target in _USER_FK_TABLES:
        existing = _existing_fk_name(table, column)
        with op.batch_alter_table(table) as batch:
            if existing:
                batch.drop_constraint(existing, type_="foreignkey")
            else:
                # Fresh DB / schema reset: there is no existing FK to
                # drop. Skip the drop and create the new one directly.
                pass
            batch.create_foreign_key(
                _new_fk_name(table, column),
                target,
                [column],
                ["id"],
                ondelete="CASCADE",
            )


def downgrade() -> None:
    """Re-create the FK without ondelete to restore NO ACTION semantics.

    Looks up the existing constraint by inspector — by this point it
    should always be the canonical name we set in upgrade(), but a
    direct DB tweak could have renamed it.
    """
    for table, column, target in _USER_FK_TABLES:
        existing = _existing_fk_name(table, column) or _new_fk_name(table, column)
        with op.batch_alter_table(table) as batch:
            batch.drop_constraint(existing, type_="foreignkey")
            batch.create_foreign_key(
                _new_fk_name(table, column),
                target,
                [column],
                ["id"],
            )
